
import { join } from 'node:path';
import { readdir, readFile, writeFile } from 'node:fs/promises';

const iconDir = rel('../node_modules/bootstrap-icons/icons/');
const iconList = (await readdir(iconDir)).filter(f => /\.svg/.test(f)).map(f => join(iconDir, f));
const icons = await Promise.all(
  iconList.map(src => (async () => {
    const data = await readFile(src, 'utf8');
    const parts = src.replace(/.*\//, '').replace(/\.svg$/, '').split('-');
    if (/^\d/.test(parts[0])) parts[0] = `number${parts[0]}`;
    let name = parts.shift() + (parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('') || '');
    return { src, data, name };
  })())
);
console.warn(icons[0]);

const iconsJS = rel('../icons.js');
const content = `
// !!! --- DO NOT EDIT --- !!!
// The content of this file is generated by running ./utils/generate-icons.js.
// Edits to this file will be lost.
// !!! --- DO NOT EDIT --- !!!

import { html } from 'lit';
import './components/icon.js';

export function iconWrapper ({ slot }, svg) {
  return html\`<sm-icon slot=\${slot}>\${svg}</sm-icon>\`;
}

${ icons.map(({ name, data }) => `export const ${name} = (params = {}) => iconWrapper(params, html\`${data}\`);`).join('\n\n') }

`;

await writeFile(iconsJS, content);

function rel (pth) {
  return new URL(pth, import.meta.url).toString().replace(/^file:\/\//, '');
}
